### ISSUE TITLE
Step size- Only one decision per step?

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#1]
In the UrbanSwarm simulation, vehicles can only take one decision per time step. This means that if it takes a vehicle 1 minute to get to the next intersection and the time step is 5 minutes, the vehicle will wait for 4 min at the intersection until it can take the next decision. @agrignard How did you handle this in the Urban Swarms simulation?

We have tried a couple of things to solve this, but for now thought the best was to at least have an estimate of the error that we are introducing. For that, we got a good average of what is the mean segment distance (from intersection to intersection) by running a long simulation and tracking the agents, and with that we can estimate the error as a function of the time step. _Error in the average segment = step size – time that it takes to do the average segment_

For example: If the average distance is 100m and the vehicle speed is 10 km/h, it will take 36 s to do this distance. In this case, with a step size of 1 min, on an average step, the vehicle would lose 24s per vehicle per intersection, with 2 minutes of step size we would lose 84s, etc…. Therefore, the ideal step size is 36s or less so that a vehicle takes the 20s on a certain road it will wait for 16s and so on, and the least favorable case is that if it takes 37s it will wait for 35s…

**Comment by agrignard** [comment]
I don't remember what we had for UrbanSwarms. I can understand 1sec is a lot especially if you have a new area. But what is the total time you want to simulate? Is it one day or a specific hour?

**Comment by NaroaCS** [comment]
We want to simulate at least one day, because I guess a week is too much, right? Especially considering that we want to be able to run batch experiments.
