### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#16]
Just noting some general questions for all of us:
Parameters.gaml
Why do we need a [followDistance](https://github.com/CityScope/VehicleClustering/blob/cf115570c57a273b51a403967a9fb851e417095d/CS_CityScope_GAMA/models/Parameters.gaml#L55)
Why do we check so many parameters in order to decide to get a charge ? [this](https://github.com/CityScope/VehicleClustering/blob/cf115570c57a273b51a403967a9fb851e417095d/CS_CityScope_GAMA/models/Parameters.gaml#L62)  one and [this](https://github.com/CityScope/VehicleClustering/blob/cf115570c57a273b51a403967a9fb851e417095d/CS_CityScope_GAMA/models/Parameters.gaml#L63) other one
What is [rideDistance](https://github.com/CityScope/VehicleClustering/blob/cf115570c57a273b51a403967a9fb851e417095d/CS_CityScope_GAMA/models/Parameters.gaml#L66)

Agents.gaml
Does [this](https://github.com/CityScope/VehicleClustering/blob/faf87dd836e47b3313ff1bc9963dc5629e1f56c8/CS_CityScope_GAMA/models/Agents.gaml#L70)  line check if there are bikes available?

**Comment by NaroaCS** [comment]
Hi @jmugicagonz ! I think I saw you changed this in the code following @ptaillandier 's suggestion. Did it work well?
Thank you, @ptaillandier ! 👍

**Comment by agrignard** [comment]
Can we close this issue?

**Comment by jmugicagonz** [comment]
Hi! Sorry I did not reply, I just saw this. Thanks a lot for your help!! :) @agrignard @ptaillandier
