### ISSUE TITLE
Output for Tangible Swarms

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#19]
Hey @agrignard !

I've been checking how to get a proper output from the simulation so that Edu can run it on the Tangible swarms and I might need a bit of help from you. He explained to us that what he needs is either a Gama simulation that he can replicate running it in real time or a log file, that would contain data with a high frequency (sim step around 10Hz) that gives him info on:
a) the speed and angle of each vehicle b) the rest of the variables that we want to represent  (i,e, status, battery level).  This would be the data that he would send to the robots.

I have two questions:

- What do you think would be the best way of saving this information? Should we use a -csv file or would it be better to use something like a Gama monitor or an inspector? 

- Right now the agents are generated at a random place at a random time, but we want to be able to save and replicate this simulation so that we identify some scenarios that we want to test with the Tangible Swarms. Is this what the saveSimulaition is supposed to do? And then we could run that .gsim?

**Comment by NaroaCS** [comment]
Thank you @agrignard ! 
I understood from @edcafenet that if we want to choose some scenarios (i.e., a robot runs out of battery and another robot comes to share chage with it) we could run a simulation, check when and where these interesting scenarios happen and then save it in a way that we'd be able to replicate them, that's why I was thinking that maybe we should save the simulaition or make it deterministic. But maybe if we already save all the important data in a .csv he can use that for the robots and wouldn't need to run a Gama experiment at the same time?

**Comment by NaroaCS** [comment]
Also, @agrignard if I might ask another question following up on this,, do you have any thoughts on how we might know the position and **angle** (direction) of each agent at each timestep?
We're using goto() and follow() functions, for instance:

https://github.com/CityScope/VehicleClustering/blob/36da09896a46481007dbe22c7f9359d244a4fa2b/CS_CityScope_GAMA/models/Agents.gaml#L391

https://github.com/CityScope/VehicleClustering/blob/36da09896a46481007dbe22c7f9359d244a4fa2b/CS_CityScope_GAMA/models/Agents.gaml#L409

**Comment by agrignard** [comment]
What you need is described here in the gama documentation:
https://gama-platform.org/wiki/BuiltInSkills#moving

This are the built-in attribute that you have for any agent using a moving skills which is your case. So you can directly access to ```location```and ```heading```

**Comment by NaroaCS** [comment]
Ok, awesome! I didn't know about the` heading` attribute- Thanks!
