### ISSUE TITLE
Change demand

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#2]
Maybe we should have a demand that is more realistic than a random on a window; do have demand data based on BlueBikes usage and for this simulation realism in the demand is important.

**Comment by NaroaCS** [comment]
Hi @tmightyquinn
Just uploaded the files. Sorry, they did not upload last time because of the .gitignore. 
With the new file structure, the demand .csv are under CS_CityScope_GAMA>includes>Demand

And, yes, they are ordered by start time

**Comment by agrignard** [comment]
What is the status of this issue? If it's fixed we can close this issue

**Comment by NaroaCS** [comment]
We left it for next steps, I need to catch up with this and implement a more realistic demand.

**Comment by NaroaCS** [comment]
Implemented in branch new-demand, will merge with main
