### ISSUE TITLE
Charging at station

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#21]
TODO: check if chargingStationCapacity is working
It is used here: https://github.com/CityScope/VehicleClustering/blob/d5fd379e97a3d7e890614b747dfca9c271dbf165/CS_CityScope_GAMA/models/Agents.gaml#L84
What is the status of the bikes if they're waiting?

**Comment by agrignard** [comment]
Is this issue still active? If not please feel free to close it
