### ISSUE TITLE
Duplicate index in log file

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#25]
in bikeChargeEvents.csv

![imagen](https://user-images.githubusercontent.com/47645142/140072157-9e6ee693-5c84-4d5e-9851-c1e368dc8d38.png)

**Comment by agrignard** [comment]
What is the issue here?

**Comment by agrignard** [comment]
If 2 event happen in the same cycle you will have the same id if you use the cycle as an id , but there are maybe other ways to create a unique id even if the event is happening as the same time (e.g concatenating the id of the agent on top of the time or picking a random number, using the cycle+time in ms, etc etc) ?

**Comment by agrignard** [comment]
Any update on this issue?

**Comment by NaroaCS** [comment]
It stopped happening
