### ISSUE TITLE
Pheromone levels always stay at 0

### ISSUE THREAD

**Issue by larryshi02** [CityScope/VehicleClustering#26]
It seems that the pheromone levels at every intersection always stay at 0 in all directions. Maybe there's a bug in the [updatePheromones](https://github.com/CityScope/VehicleClustering/blob/79fd8631375705f3f324979555b1b15d1ec891b5/CS_CityScope_GAMA/models/Agents.gaml#L524) logic?

**Comment by agrignard** [comment]
Any update on this part?

**Comment by NaroaCS** [comment]
Fixed by @jmugicagonz
