### ISSUE TITLE
Metadata file commited

### ISSUE THREAD

**Issue by agrignard** [CityScope/VehicleClustering#27]
Dear all,

I just saw some commit like the last one where many meta files from GAMA are actually commited on this repo.

@jmugicagonz Is there a reason why those data are commited?

**Comment by NaroaCS** [comment]
I don't know what happened but I also saw that this metadata commited and wasn't allowing me to pull. Could you check this @jmugicagonz please? This might have caused your updates not to be saved properly; if I run the current code the pheromone values stay at 0

**Comment by NaroaCS** [comment]
Fixed by including it in the .gitignore file
