### ISSUE TITLE
Pheromone traces

### ISSUE THREAD

**Issue by larryshi02** [CityScope/VehicleClustering#28]
I'm wondering what is the syntax I can use to call a method when I'm displaying an experiment.

For example, if I want to add a facet to the [bike](https://github.com/CityScope/VehicleClustering/blob/f35533e822b7fe5fdb0e072ff62537472731fb28/CS_CityScope_GAMA/models/clustering.gaml#L179) species that takes the value returned by the function [availableForPlatoon](https://github.com/CityScope/VehicleClustering/blob/f35533e822b7fe5fdb0e072ff62537472731fb28/CS_CityScope_GAMA/models/Agents.gaml#L273), is there a way I can call that function? Or, if there's a way to simply call a parameter within the bike species, that would be helpful too.

**Comment by agrignard** [comment]
Hi @larryshi02 sorry I am not sure to understand your question. 

What do you mean by:
- "to call a method when I'm displaying an experiment." ? you mean calling a method while the simualtion is running? To do so you can have a reflex in the global for instance
"if I want to add a facet to the bike species" which facet are you talking about?

**Comment by NaroaCS** [comment]
Hi @larryshi02 , I think you already figured out how to do this, right? 
Can we close the issue?

**Comment by larryshi02** [comment]
@NaroaCS @agrignard 

I've been working on this for a bit and haven't been able to figure this out. I'll clarify my question:

I want to add the "trace" keyword to [this](https://github.com/CityScope/VehicleClustering/blob/c7d60944ef5e0b83f6025ff400d4596901c96902/CS_CityScope_GAMA/models/clustering.gaml#L174) line, which takes an integer. I want this integer to be the average pheromone level of the tagRFID in all directions, which can be calculated using this method within the tagRFID species: 
`	float average {
		float sum <- 0;
		float length <- 0;
		loop k over: neighbors{
			sum <- sum + pheromoneMap[k];
			length <- length + 1;
			
		}
		float avg <- sum/length;
		return avg;
	}`

I'm unsure of the syntax for this. Any help is appreciated.

**Comment by agrignard** [comment]
Ok it helps however you might not use trace here but write some code in the aspect of the tag

```trace``` is a facet that is global if you use an integer M it means that all the tagRFIDS will be drawn at step N plus the drawing of the t=N-1 with a transparency of 90% t=N-2 transparency of 80% and so on until t=N-M with a transparency of 0%. That's actually why it's called ```trace```

So it's a global concept that will be applied to the all population of tagRFID.

I have the feeling here that the average is a value unique for each tag. Which means you might want to use the value average in the aspect  of the tag ``` aspect base ``` where 

does it help?

**Comment by agrignard** [comment]
@larryshi02 did you figure out this one?

**Comment by larryshi02** [comment]
@agrignard 

Thanks for your help. I've been working on this and it definitely helps, but I'm still unsure how the program knows how to find the average value in `aspect base` (i.e. how does the trace method know what value to display with transparency)? Do I make a variable within `aspect base` that I call somewhere else?

**Comment by agrignard** [comment]
Can you point me to the part of the code doing this? It will be easier 

Is the average value for each RFID or it's a global and unique value?

Also what about drawing on a paper what you want o achieve visually? It's hard for me to figure out excatly what you want to display.

**Comment by agrignard** [comment]
Is this issue still active? If not please feel free to close it
