### ISSUE TITLE
CSVs in "data" folder uploaded

### ISSUE THREAD

**Issue by larryshi02** [CityScope/VehicleClustering#29]
@jmugicagonz 

I pushed some code that affects pheromone visualizations and the CSVs in the "data" folder were also unintentionally uploaded. Do you know why the folder was updated? Maybe it has something to do with .gitignore?

**Comment by agrignard** [comment]
If you don't specify to exlcude a specific folder it is normal that if you have new file in data there are uploaed. If you don't want to push the data that are contained in this folder you need to edit the gitignore indeed. So far there is no reference to the folder data in the gitignore
Any update on this part?

**Comment by NaroaCS** [comment]
@jmugicagonz did you modify the .gitignore file? I think the data folder was included the .gitignore before

**Comment by NaroaCS** [comment]
It was excluded but still had to remove the files by 
git rm -rf --cached .
git add .
