### ISSUE TITLE
Change map

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#3]
Switch the map to an area larger than Kendall to have more realistic bike trips. 
Since we will have an OD matrix based on Bluebikes data, we can have an area that at least includes. As a first iteration for the demand, I chose the following area:
lat_min = 42.355013
lat_max = 42.369192
lon_min= -71.117067
lon_max = -71.075183

**Comment by jmugicagonz** [comment]
Changing the map to a larger one has given the following issues:

- There is sth related to the roads shape files that does not work as the former one and gives distance problems.
- The simulation starts to consume more and mor ememory as it goes by (don't know why) and there is a moment where it requests to close the experiment.
- Most of the trips are not served. This should be fixed chaging the number of agents or the range a person has to call for a bike


Need investigation

**Comment by jmugicagonz** [comment]
I also need to check if we can have a map delimited by lat and long as you propose

**Comment by agrignard** [comment]
I understand the fact that you need to enlarge the area of interest just keep in mind that the current map is in sync with the Volpe table, maybe one day you might want to integrate your simulation on the volpe table.

Not sure what is the best way to do it but maybe you can have two settings, one with the big map and one with cambridge. Or yu can define the world shape with Cambridge but still keeping somehow the volpe one ine the simulation.

let me know if you need any help to do so.

**Comment by agrignard** [comment]
Is it still an ongoing issue? If not we can close this issue

**Comment by NaroaCS** [comment]
For now we're keeping Kendall
