### ISSUE TITLE
How to Deactivate Battery Sharing

### ISSUE THREAD

**Issue by larryshi02** [CityScope/VehicleClustering#30]
@jmugicagonz 

Juan,

Do you know if there is an easy way to deactivate battery sharing in the Gama code? I am currently working on setting up experiments that don't incorporate battery sharing.

Thanks.

**Comment by NaroaCS** [comment]
Implemented but should be reviewed, it somehow affects the station charge or its output because charge distance is zero and even if there is a log of bikes charging, the battery gain does not compute correctly

**Comment by NaroaCS** [comment]
Fixed
