### ISSUE TITLE
Log files *100

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#33]
Hi @jmugicagonz,

I remember that you mentioned something about multiplying some floats by a 100 and casting to int, I see that you did this for instance here:

https://github.com/CityScope/VehicleClustering/blob/47e4ef6df751897bb5dd5beb9cbc98641353799b/CS_CityScope_GAMA/models/Loggers.gaml#L369

What was the issue? Is there any other way to fix it? Otherwise I guess we're getting values 100 times higher than they should be.

**Comment by NaroaCS** [comment]
There is also this other notw that I think you wrote:

https://github.com/CityScope/VehicleClustering/blob/47e4ef6df751897bb5dd5beb9cbc98641353799b/CS_CityScope_GAMA/models/Loggers.gaml#L486

Could you please check if this was done already?

**Comment by agrignard** [comment]
Is this issue still active? If not please feel free to close it
