### ISSUE TITLE
Wait times > max

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#36]
Some wait times are above the maximum wait time, we need to review how we filter the bikes when deciding which one to assign

**Comment by NaroaCS** [comment]
I've changed the distance to graph distance but still there are some users around 3/400 in which this is not respected. I need to dig deeper

**Comment by NaroaCS** [comment]
There's a delay bewteen requesting a bike and it statting the trip

**Comment by NaroaCS** [comment]
That delay was due to the long time step. 
- There was an error in how the maxDistance was calculated starting from maxWaitTime, that has been fixed
- Even if we use the roadNetwork to calculate the distance and the distance is below the max, sometimes it takes longer than it should to do that distance (eg. 8-10 min when it should be 4)

**Comment by NaroaCS** [comment]
@agrignard

Hi Arnaud, 
I was wondering if you'd be able to help me with this. I check the distance bewteen a user and the closest available bike, if it's above maxDistance the trip is not served. However sometimes (like 6-10 times every 400 trips), even if the distance is below the maximum, then it takes longer than it should to do that distance at the corresponding speed (eg. it takes 8-10 min instead of 4-5).  
I've checked that the bike is actually doing the pickup properly and all the calculations are based on the roadNetwork, there seems to be something just related to the time that it takes to do that distance.

This is how the maxDistance condition is checked:

https://github.com/CityScope/VehicleClustering/blob/3acbf0c15f5efe7abc8e1ad9c72ee56c866d70ae/CS_CityScope_GAMA/models/Agents.gaml#L55

The distance for that is calculated with this function:
https://github.com/CityScope/VehicleClustering/blob/3acbf0c15f5efe7abc8e1ad9c72ee56c866d70ae/CS_CityScope_GAMA/models/Agents.gaml#L8

And this is where it's executed:

https://github.com/CityScope/VehicleClustering/blob/3acbf0c15f5efe7abc8e1ad9c72ee56c866d70ae/CS_CityScope_GAMA/models/Agents.gaml#L449

**Comment by agrignard** [comment]
Is this still an issue?
