### ISSUE TITLE
Launching experimients in Server

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#38]
Hi @agrignard !

A quick question: I want to run the experiments in the Andorra server, and I was wondering if Gama is already installed yet.
If it is --> Do I need to update it? What’s the command line to update it?
If it is not --> How do I need to install it? I guess I’ll have to clone it from GitHub, right? I can’t find how to install it through command line

Thank you!!

**Comment by agrignard** [comment]
Hi @NaroaCS as far as I know Gama is not install on the Andorra server. To do so you might need to see with the librarian of the server to install it and then yes Gama is designed to be use in headless mode (meaning no interface or display)

The documentation for the headless can be found here
https://gama-platform.org/wiki/Headless

**Comment by NaroaCS** [comment]
Thank you @agrignard ! 
Just a follow-up question: Isn't there the possibility of installing Gama on the server by myself? Cloning it from GitHub through the terminal and then extracting the .zip?

**Comment by agrignard** [comment]
@NaroaCS I don't think you want to clone the gama repo (this is where all the source are strored. In order to run it you need to install eclipse etc etc) what you want to place in the folder is the 'executable' of Gama which I call a release

**Comment by NaroaCS** [comment]
Awesome, thanks a lot @agrignard !
