### ISSUE TITLE
Running bacth experiments in headless mode

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#39]
Hi @agrignard, 

Sorry to bother you! Trying to un Gama in headless mode I get this error:
`.java.lang.ClassCastException: msi.gama.kernel.experiment.BatchAgent cannot be cast to msi.gama.kernel.simulation.SimulationAgent`

The experiment that I'm trying to run is a batch experiment, but does this error mean that I can't run a batch experiment in headless mode? I've checked the Gama documentation and I see that it says: "For more systematic parameter values samples, you should turn towards a more adapted tool such as GAMAR, to generate a ExperimentFile.xml with a huge number of simulations." Is this what I would need to do, instead of running a batch experiment?

Just in case it helps, this is my .xml file: 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Experiment_plan>
        <Simulation id="2" sourcePath="../../../VehicleClustering/CS_CityScope_GAMA/models/clustering.gaml" until="cycle >= numberOfDays * numberOfHours * 3600 / step" experiment="batch_experiments_headless">
          <Parameters>
          </Parameters>
          <Outputs>
          </Outputs>
        </Simulation>
</Experiment_plan>
```

And this is the batch experiment that I want to run (defined in my clustering.gaml file):

https://github.com/CityScope/VehicleClustering/blob/c29846060af0bd142aa728f874c1b6b12530df54/CS_CityScope_GAMA/models/clustering.gaml#L155

**Comment by NaroaCS** [comment]
Hi @agrignard ! I just wanted to send you a friendly reminder of this issue :)

**Comment by agrignard** [comment]
Hi @NaroaCS , I am not sure to be able to reproduce this issue.

Can you first tell me which version of GAMA you are using. I know some recent change has been made on the headless and batch feature. You might want first to reinstall one of the latest Gama Version (here https://github.com/gama-platform/gama/releases/tag/1.8.2)
