### ISSUE TITLE
Specifying CPUs in headless mode

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#40]
Hi @agrignard !

Could you, please, help me with a question on GAMA headless mode?

When I run the simulations in headless mode on the server, I always see the following note: `Number of cpus used:1 (available: 4)`
I have specified the number of cores as indicated here (https://gama-platform.org/wiki/Headless):
eg)` bash gama-headless.sh -hcp 4 samples/pheromone-random.xml outputHeadless`
I have tried both with 4 and 16 but it keeps saying  `Number of cpus used:1 (available: 4)`

The specs of the server are the following:
```
CPU(s):              4
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
```

How can I use all the 4 available cpus? 

Thank you!

**Comment by agrignard** [comment]
Is it possible to see your pheromone-random.xml ?

**Comment by NaroaCS** [comment]
Yes: 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Experiment_plan>
        <Simulation id="2" sourcePath="../../../VehicleClustering/CS_CityScope_GAMA/models/clustering.gaml" until="cycle >= numberOfDays * numberOfHours * 3600 / step" experiment="batch_experiments_random">
          <Parameters>
          </Parameters>
          <Outputs>
          </Outputs>
        </Simulation>
</Experiment_plan>
```

The `batch_experiments_random` is a batch simulation

**Comment by NaroaCS** [comment]
Thank you @RoiArthurB and @agrignard, your explanation was very clear! 👍 
I was already saving the output in .csv so it is the perfect solution for my case and I am already using it !
Thank you very much

**Comment by NaroaCS** [comment]
Hi @RoiArthurB !

I have been using for a while now the command that you suggested here to run batch experiments. In general, it worked well and has been very helpful for me. However, recently for one of the experiments it didn't cover all the sets of parameters and it duplicated some of them. 
I am fixing it manually but I just wanted to let you know in case there's any bug.

Thanks!

**Comment by RoiArthurB** [comment]
Hi @NaroaCS 

With the tiny information you're giving me, I can't tell anything of what happened to you... 😅😅😅 What version ? With XML or `-batch` command ? How many simulations you have to run ? On how much of RAM (used/needed per sim) ? etc etc...

If you think that's a bug, and you can re-do it, feel free to open an issue on https://github.com/gama-platform/gama :smile:

**Comment by NaroaCS** [comment]
haha upss....I'm sorry 🙈 I didn't know what info you needed! 
I will try to replicate it, and will post in the Gama GitHub if I do. Thanks @RoiArthurB !
