### ISSUE TITLE
Rearrange folders

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/VehicleClustering#6]
Hi @jmugicagonz,

I removed the main folder CS_CityScope_GAMA so that we have one level less of folders; so now the readme and the folders models, includes etc. are at the same level. I also removed some data from the includes folder, which was related to Energy, the GameIT model etc. I think we can still clean it up a bit more but I'm afraid of deleting something that you consider important. Could you review this and maybe simplify a bit more the structure of the files? I think we can just have three folders under includes: 

- demand: .csv files containing the origin, destination and time
- graph: road networks
- buildings: shapefile of the buildings

Also, we can probably just have the current code under models (and not have a subfolder CityScope) and the results can be in a separate folder, so that in the main folder we would have:

- includes
- images
- models
- results
- headless? -> Do you know what this is? I think it's from the previous code, I think we can remove it

Then we should double-check that the paths are correctly set in the code.

Note: The new demand is under includes>Demand but there is also some graph and building maps from the previous simulation in this folder too in case you want to check them out.

**Comment by jmugicagonz** [comment]
I don't know if it's just my computer but now it does not recognize any projects

**Comment by jmugicagonz** [comment]
I believe the include foelrs should have two folders inside:

City: different cities included for the simulations, with everything related to each map: roads, bounds, buildings and maybe even bluebikes current stations.
Demand: .csv files containing the origin, destination and time
